### ISSUE TITLE
Use of 'collective.person' namespace on collective for a new addon

### ISSUE THREAD

**Issue by fredvd** [collective/collective.person#1]
@bosim @sunew  For several website projects and also plone.org extensions,  kitconcept wants to develop a new flexible person/contact focussed Plone 6 add'on with a generic content type that can be extended with behaviors. 

We checked current implementations, there is collective.contact.* and collective.person. We would very much like to use collective.person, but the namespace has already been taken by this repo.  The collective.person add'on has never seen a release on pypi though and the last commits were almost 10 years ago. 

Do you still use this add'on in any projects for which you created it?  If not, or only a few, would it be ok for you if you can make a fresh interim release of this add'on, we rename it here on collective and then use the free collective.person namespace for the new to be developed Plone 6 add'on?  

cc: @ericof @davisagli

**Comment by jsbueno** [comment]
IIRC, we started these because i wanted a way to have a single, simple to use "email" field, and the existing way was somewhat convoluted. 

@ericof will know better, but as far as I am concerned this can go. 
(There were projects pulling from here, I don't think exist anymore, but maybe creating a tag with the current project, and changing everything with a new version number won´t do bad?)

**Comment by ericof** [comment]
@jsbueno I'm pretty sure this is not "our" project :-D

**Comment by ericof** [comment]
@fredvd I think it is safe to assume we can reuse this.

**Comment by sunew** [comment]
@fredvd a bit late reply here, but please go ahead:)
